### ISSUE TITLE
Broken system tray

### ISSUE THREAD

**Issue by jazz4web** [lxde/lxpanel#62]
Hello, everyone...

I use Debian sid with LXDE on board. After the last update I watch the broken system tray in LXDE panel. Look at this couple of screen shots.

![no flag](https://codej.ru/picture/9Ylp5zuzgF.png)

![with flag](https://codej.ru/picture/a1EN2lWpWp.png)

If the screen resolution on my monitor is 1366X765 and the flag installed, there is no tray at all in the panel.

![big resolution](https://codej.ru/picture/cu1MmeqDTV.png)

There is the next strings in run.log file:

```
** (lxpanel:1025): WARNING **: 08:10:08.357: task button : X error
** (lxpanel:1025): WARNING **: 08:10:59.260: lxpanel : X error: BadWindow (invalid Window parameter)
** (lxpanel:1025): WARNING **: 08:10:59.260: lxpanel : X error: BadWindow (invalid Window parameter)
** (lxpanel:1025): WARNING **: 08:10:59.260: lxpanel : X error: BadWindow (invalid Window parameter)
(lxpanel:1025): GLib-GIO-CRITICAL **: 08:11:07.860: GFileInfo created without standard::edit-name
(lxpanel:1025): GLib-GIO-CRITICAL **: 08:11:07.860: file ../../../gio/gfileinfo.c: line 1743 (g_file_info_get_edit_name): should not be reached
(lxpanel:1025): GLib-GIO-CRITICAL **: 08:11:07.860: GFileInfo created without standard::size
(lxpanel:1025): GLib-GIO-CRITICAL **: 08:11:07.860: file ../../../gio/gfileinfo.c: line 1846 (g_file_info_get_size): should not be reached
(lxpanel:1025): GLib-GIO-CRITICAL **: 08:11:07.860: GFileInfo created without standard::is-symlink
(lxpanel:1025): GLib-GIO-CRITICAL **: 08:11:07.860: file ../../../gio/gfileinfo.c: line 1677 (g_file_info_get_is_symlink): should not be reached
(lxpanel:1025): GLib-GIO-CRITICAL **: 08:11:07.861: GFileInfo created without standard::is-backup
(lxpanel:1025): GLib-GIO-CRITICAL **: 08:11:07.861: file ../../../gio/gfileinfo.c: line 1655 (g_file_info_get_is_backup): should not be reached

```

Before the last update everything worked fine. Any help would be wonderful!

**Comment by ib** [comment]
This is because Debian now compiles LXDE with GTK+ 3, even though not all components have been fully prepared for GTK+ 3 yet.

**Comment by jazz4web** [comment]
Okay, I understand... Thank you for your answer. The only question is will those components be fully prepared and if so, when? Or do I have to look for another solution for my desktop?

**Comment by ib** [comment]
> The only question is will those components be fully prepared

This is the plan.

> and if so, when?

I can't tell you. Development capacity is limited.

**Comment by jazz4web** [comment]
OK. I love LXDE... So, I'll stay tuned! :)

**Comment by jrchamp** [comment]
Based on the discussion in Debian Bug 1052376, #38 may resolve this issue.

Thank you so much for LXDE!

**Comment by galtgendo** [comment]
> Based on the discussion in Debian Bug 1052376, #38 may resolve this issue.
> 

The mentioned commit just breaks things in a different way.

With that commit, while panel is set to 100% width, pager plugin covers (for example) systray and clock if they come after the pager.

**Comment by galtgendo** [comment]
The things rarely get fixed by themselves, so would you mind pointing out a commit made since I commented that would make a difference here ?

Cause I don't see it in this repo, at least not on master.

I'm not on Debian and my setup is pretty much as simple as it gets: lxsession, lxpanel, openbox (technically two monitors, but I keep one of them off most of the time - it's pretty small (by today's standards), so it's mostly good for triggering multi-monitor bugs).

Unless that #38 made a difference for that poster, but as I've said, that one just generates a different bug.

**Comment by jazz4web** [comment]
> Do you still have this issue?

I do, I got used to this issue. So, the panel is still broken, because things rarely get fixed by themselves.

**Comment by kurokawachan** [comment]
Hello, do you have a screen shots? 
I don't understand the problem. 

Debian sid  is not a stable debian. It highly likely not an issue from lxde.    

I tried Debian sid and did not found this issue. Are you on latest release?

I am not sure if this issue is from two monitors. I set up a vm with two monitors, still not have this issue

**Comment by jazz4web** [comment]
> Hello, do you have a screen shots?
No, sorry. My picture hosting is unavailable, I could not pay for the server. And I don't want to use any public picture hosting. Again, I am sorry.


> Debian sid is not a stable debian. It highly likely not an issue from lxde.
Actually it is an LXDE issue starting from Debian trixie/sid, on Debian bullseye everything works fine.

> I tried Debian sid and did not found this issue. Are you on latest release?
Debian sid is rolling. Yes, I upgrade it every 2 weeks. The issue is still there - panel is broken. It works almost fine, but looks awful.

**Comment by kurokawachan** [comment]
Hello @jazz4web 

It looks like it is a different issue from what it was first created?

It feels like this issue https://github.com/lxde/lxpanel/issues/76

Searching Debian Bug
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1052050

Would you have a look and see if this is the same?

**Comment by jazz4web** [comment]
Look here, my friend... This is my LXDE panel.

![no-flag](https://github.com/user-attachments/assets/22f792d1-661c-415e-9776-e56297e58269)

There is no flag, but there is the system tray. Now I put the flag.

![flag](https://github.com/user-attachments/assets/0211003b-b56d-47d3-82a4-a7e36701e300)

Uh-oh... Where is the system tray? Nothing. That is it. I have nothing else to say.

**Comment by kurokawachan** [comment]
Thanks, now I understand what is going on. And I still believe it might be same issue in https://github.com/lxde/lxpanel/issues/76

 

I might be wrong, but I think inside the function `panel_start_gui`

https://github.com/lxde/lxpanel/blob/ffd815fc2d30a5fe339e5c927060a14cdc88e345/src/panel.c#L1666C1-L1673C13


before we use `gtk_window_present`

We should use `gtk_window_set_default_size` to set the width and height. 
```

    /* window mapping point */
    p->visible = TRUE;
    _calculate_position(panel, &rect);
    gtk_window_move(GTK_WINDOW(panel), rect.x, rect.y);
    gtk_window_set_default_size(GTK_WINDOW(panel),rect.width,rect.height);
    gtk_window_present(GTK_WINDOW(panel));

```

It would fix the issue.

**Comment by jazz4web** [comment]
I am not a C-programmer. I don't know what is happening inside the black box of GTK. I just hope LXDE developers will change the situation till Debian trixie release. As I sad, I got used to this issue. It works almost fine, looks awfull. But LXDE is my favorite one, I don't want anything else, especially LXQt.

**Comment by ib** [comment]
> I just hope LXDE developers will change the situation till Debian trixie release.

That is the plan, time permitting.

**Comment by ib** [comment]
Fixed.

**Comment by galtgendo** [comment]
As I've mentioned in an earlier comment, I'm 95%+ sure that's incorrect. 
Let me open a *new* bug about this.
